### ISSUE TITLE
Angular 12+ support

### ISSUE THREAD

**Issue by TomaszCz** [guzmanoj/quar#1]
Hi!

Not sure if you are aware, but your package doesn't work with angular 12 or above :)

`npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.2.13" from @altack/quar@0.0.7
npm ERR! node_modules/@altack/quar
npm ERR!   @altack/quar@"0.0.7" from the root project`

Would you accept PR with fix :)?

**Comment by wall-street-dev** [comment]
Sure thing @TomaszCz!

**Comment by wall-street-dev** [comment]
Feel free to use v1.3.x if you are on Angular 13 already.
